---
services:
  hytale:
    build:
      context: ..
      dockerfile: Dockerfile
    image: indifferentbroccoli/hytale-server-docker
    restart: unless-stopped
    container_name: hytale
    #stop_grace_period: 30s # for dev i dotn care bout gracefull shutdown
    ports:
      - 5520:5520/udp
    env_file:
      - ../.env
    volumes:
      - ../server-files:/home/hytale/server-files
      - ../scripts:/home/hytale/server  # use scripts from host dir. # dev only
    stdin_open: true
    tty: true
